### ISSUE TITLE
App crashing on Post upload

### ISSUE THREAD

**Issue by anthonymiyoro** [N-itotia/Androidblogapp#1]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.blogapp, PID: 3764
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at com.example.blogapp.Activities.Home$3$1$2.onSuccess(Home.java:256)
        at com.example.blogapp.Activities.Home$3$1$2.onSuccess(Home.java:247)
        at com.google.android.gms.tasks.zzn.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616`

**Comment by N-itotia** [comment]
Noted

**Comment by N-itotia** [comment]
Fixed the real-time database on Firebase
